#!/bin/sh
#
# Sync agent personas from .agents/personas/ to tool-specific config formats
#
# This script handles:
# - Reading canonical persona definitions from .agents/personas/*.md
# - Generating .claude/agents/*.md files with Claude Code frontmatter
# - Generating AGENTS.md for Codex and other tools that read it
#
# Canonical persona format (.agents/personas/<name>.md):
#
#   ---
#   name: <agent-name>
#   description: <one-line routing description>
#   tools: Read, Grep, Glob, Bash, Edit, Write
#   model: opus | sonnet | haiku
#   ---
#
#   <body: role instructions in plain markdown>
#
# Exit codes:
# - 0: Success
# - 1: Source directory not found
# - 2: No persona files found
# - 3: Output directory creation failure
# - 4: Persona file missing required field
#
# Usage: ./sync-agents.sh [--source <dir>] [--dry-run]
#        ./sync-agents.sh -s <dir> -n

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults
SOURCE_DIR="$PROJECT_ROOT/.agents/personas"
CLAUDE_AGENTS_DIR="$PROJECT_ROOT/.claude/agents"
AGENTS_MD="$PROJECT_ROOT/AGENTS.md"
DRY_RUN="false"

log_info() {
    echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_error() {
    echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $1" >&2
}

usage() {
    echo "Usage: $0 [--source <dir>] [--dry-run]"
    echo ""
    echo "Options:"
    echo "  -s, --source    Directory containing canonical persona files (default: .agents/personas)"
    echo "  -n, --dry-run   Print what would be written without creating files"
    echo "  -h, --help      Show this help message"
    echo ""
    echo "Canonical persona file format (.agents/personas/<name>.md):"
    echo "  ---"
    echo "  name: my-agent"
    echo "  description: One-line routing description used by the orchestrator"
    echo "  tools: Read, Grep, Glob"
    echo "  model: sonnet"
    echo "  ---"
    echo ""
    echo "  Role instructions in plain markdown..."
    exit 0
}

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            -s|--source)
                SOURCE_DIR="$2"
                shift 2
                ;;
            -n|--dry-run)
                DRY_RUN="true"
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                ;;
        esac
    done
}

# Extract a single frontmatter field value from a file.
# Usage: get_field <file> <field>
# Returns the value or empty string if not found.
get_field() {
    _file="$1"
    _field="$2"
    # Read between the first pair of --- delimiters, find the field
    awk '
        /^---$/ { if (fm == 0) { fm = 1; next } else { exit } }
        fm == 1 && /^'"$_field"':/ {
            sub(/^'"$_field"':[[:space:]]*/, "")
            print
        }
    ' "$_file"
}

# Extract the body (everything after the closing --- of frontmatter).
# Usage: get_body <file>
get_body() {
    _file="$1"
    awk '
        /^---$/ { count++; if (count == 2) { body = 1; next } }
        body == 1 { print }
    ' "$_file"
}

# Check that a required field is non-empty.
# Usage: require_field <value> <field_name> <file>
require_field() {
    _val="$1"
    _field="$2"
    _file="$3"
    if [ -z "$_val" ]; then
        log_error "Missing required field '$_field' in $(_file)"
        exit 4
    fi
}

write_file() {
    _path="$1"
    _content="$2"
    if [ "$DRY_RUN" = "true" ]; then
        echo "--- [dry-run] would write: $_path ---"
        echo "$_content"
        echo ""
    else
        printf '%s\n' "$_content" > "$_path"
    fi
}

generate_claude_agent() {
    _persona="$1"
    _name="$(get_field "$_persona" "name")"
    _description="$(get_field "$_persona" "description")"
    _tools="$(get_field "$_persona" "tools")"
    _model="$(get_field "$_persona" "model")"
    _body="$(get_body "$_persona")"

    require_field "$_name" "name" "$_persona"
    require_field "$_description" "description" "$_persona"

    # Build frontmatter — only include optional fields if present
    _frontmatter="---
name: $_name
description: $_description"

    if [ -n "$_tools" ]; then
        _frontmatter="$_frontmatter
tools: $_tools"
    fi

    if [ -n "$_model" ]; then
        _frontmatter="$_frontmatter
model: $_model"
    fi

    _frontmatter="$_frontmatter
---"

    _out_file="$CLAUDE_AGENTS_DIR/${_name}.md"
    _content="$_frontmatter
$_body"

    log_info "  claude: $_out_file"
    write_file "$_out_file" "$_content"
}

generate_agents_md() {
    _personas_list="$1"

    _header="# AGENTS.md

This file defines agent personas available in this repository.
It is auto-generated by scripts/sync-agents.sh from .agents/personas/.
Do not edit directly — edit the source files in .agents/personas/ instead.

---
"

    _body=""
    for _persona in $_personas_list; do
        _name="$(get_field "$_persona" "name")"
        _description="$(get_field "$_persona" "description")"
        _tools="$(get_field "$_persona" "tools")"
        _model="$(get_field "$_persona" "model")"
        _role_body="$(get_body "$_persona")"

        _section="## $_name

**Description:** $_description"

        if [ -n "$_model" ]; then
            _section="$_section
**Model:** $_model"
        fi

        if [ -n "$_tools" ]; then
            _section="$_section
**Tools:** $_tools"
        fi

        _section="$_section

$_role_body

---
"
        _body="$_body
$_section"
    done

    log_info "  codex:  $AGENTS_MD"
    write_file "$AGENTS_MD" "$_header$_body"
}

main() {
    parse_args "$@"

    # Validate source directory
    if [ ! -d "$SOURCE_DIR" ]; then
        log_error "Source directory not found: $SOURCE_DIR"
        log_error "Create .agents/personas/ and add persona markdown files."
        exit 1
    fi

    # Collect persona files
    PERSONAS=""
    for f in "$SOURCE_DIR"/*.md; do
        [ -f "$f" ] && PERSONAS="$PERSONAS $f"
    done

    if [ -z "$PERSONAS" ]; then
        log_error "No persona files found in $SOURCE_DIR"
        exit 2
    fi

    PERSONA_COUNT=0
    for _ in $PERSONAS; do PERSONA_COUNT=$((PERSONA_COUNT + 1)); done
    log_info "Found $PERSONA_COUNT persona(s) in $SOURCE_DIR"

    if [ "$DRY_RUN" = "true" ]; then
        log_info "Dry-run mode — no files will be written"
    fi

    # Create output directories
    if [ "$DRY_RUN" = "false" ]; then
        if ! mkdir -p "$CLAUDE_AGENTS_DIR"; then
            log_error "Failed to create directory: $CLAUDE_AGENTS_DIR"
            exit 3
        fi
        if ! mkdir -p "$(dirname "$AGENTS_MD")"; then
            log_error "Failed to create directory for AGENTS.md"
            exit 3
        fi
    fi

    log_info "Generating Claude Code agent files..."
    for persona in $PERSONAS; do
        generate_claude_agent "$persona"
    done

    log_info "Generating AGENTS.md..."
    generate_agents_md "$PERSONAS"

    log_info "Done. Generated outputs:"
    log_info "  .claude/agents/  — Claude Code (claude.ai/code)"
    log_info "  AGENTS.md        — Codex and compatible tools"
}

main "$@"
